# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amdn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('bought_all', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
