# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amdn', '0003_item_checkouts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='count',
            new_name='count_list',
        ),
    ]
