# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amdn', '0004_auto_20180718_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
    ]
