# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amdn', '0005_auto_20180718_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
    ]
