# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amdn', '0006_auto_20180718_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='total',
        ),
    ]
