# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amdn', '0007_remove_checkout_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='checkouts',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
